### ISSUE TITLE
Exception Icon can not be found

### ISSUE THREAD

**Issue by wuppiwuppi** [liebki/MyOllamaEnhancer#1]
Hi, 
after installation from the market place (0.1.3.2) and configuration I get the below exception. 

IDE is Pycharm 2024.3 Community Edition
Build #PC-243.21565.199, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

com.intellij.diagnostic.PluginException: Icon cannot be found in 'com.intellij.icons.ExpUiIcons.Diff.MagicResolveToolbar', action 'de.liebki.myollamaenhancer.actions.CustomCodeEnhanceAction' (module=PluginDescriptor(name=MyOllamaEnhancer, id=de.liebki.MyOllamaEnhancer, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.3/MyOllamaEnhancer, version=0.1.3.2, package=null, isBundled=false))
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionError(ActionManagerImpl.kt:1612)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionError$default(ActionManagerImpl.kt:1611)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.loadIcon(ActionManagerImpl.kt:1556)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.updateIconFromStub$lambda$7(ActionManagerImpl.kt:1498)
	at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.get(SynchronizedClearableLazy.kt:28)
	at com.intellij.openapi.actionSystem.Presentation.getIcon(Presentation.java:292)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.updateIcon(ActionMenuItem.kt:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.updateFromPresentation(ActionMenuItem.kt:127)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenuInner(Utils.kt:557)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu$intellij_platform_ide_impl(Utils.kt:476)
	at com.intellij.openapi.actionSystem.impl.Utils.fillPopupMenu(Utils.kt:435)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.updateChildren(ActionPopupMenuImpl.java:170)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:126)
	at com.intellij.openapi.editor.impl.ContextMenuPopupHandler.handlePopup(ContextMenuPopupHandler.java:33)
	at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:5572)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:4388)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:4295)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4574)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by liebki** [comment]
Hi, I will look at it 👍🏻

**Comment by liebki** [comment]
Hi @wuppiwuppi,

please download and try 0.1.3.3 from the releases, the versions is in verification at jetbrains and it is not released "officially" before monday. 

<img width="348" alt="IDE > Plugins > Settings Wheel > Install from disk..." src="https://github.com/user-attachments/assets/2fbcac93-7b08-4a84-aabf-324c4c36374b">



I will not close this issue, please comment here if it is fixed or not after trying, this would help a lot.


[Releases](https://github.com/liebki/MyOllamaEnhancer/releases/tag/V0.1.3.3)

**Comment by wuppiwuppi** [comment]
Installed 0.1.3.3 from the store - exception is gone. 

I consider it solved. Thank you ;)

However, "enhance this"  only seems to work for 3-4 lines of code. Many times I get "An error occurred while executing ollama". I believe it is a timeout any my cpu-only ollama setup is too slow.

**Comment by liebki** [comment]
@wuppiwuppi nice that it works partially, however could I ask for your specs?

I use M1 Pro and I can "enhance" more than 3-4 lines with cpu-only.

**Comment by wuppiwuppi** [comment]
it is an i5-14600k with 32gb ram. originally not chosen for running llm
I also tried llama 3.2 and gemma2 - however the results on simple python code are not so satisfactory. will try more in the future but it would be nice if it can do more than 3-4 lines - even if it takes a while. maybe it could run in the background (non-blocking)

**Comment by liebki** [comment]
I will have a look into extending the processing time but I guess this is a thing internally of ollama, I didn't change anything but maybe I can find something!

Good things you bring up, surely helpful for others.
